version: "3.9"

services:
  nestjs:
    build: ./app
    container_name: nestjs_service
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      - ai_network
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  chroma_data:
