version: "3.9"

services:
  nestjs:
    build: ./app
    container_name: nestjs_service
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      - ai_network
    depends_on:
      - chromadb
      - postgres

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    networks:
      - ai_network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  chroma_data:
  postgres_data:
